site:
  name: 'Vogel Tec AB'
  site: 'https://vogel-tec.dev'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: "Vogel Tec AB"
  description: "Vogel Tec AB offers high-quality software solutions, specializing in TypeScript, Java, and more. We provide development, automation, and consulting services. Let's collaborate to achieve your software goals."
  robots:
    index: true
    follow: true

i18n:
  language: en
  textDirection: ltr

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
